import Head from "next/head";
import { useEffect } from "react";
import AOS from "aos";
import "aos/dist/aos.css";

export default function Home() {

  useEffect(() => {
    AOS.init();
  }, []);

  return (
    <>
      <Head>
        <title>Psy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="Container">
        <div className="Header">
          <a href="#course">О курсе</a>
          <a href="#reviews">Отзывы</a>
          <a href="#price">Стоимость</a>
        </div>
        <section className="Main">
          <div className="Main__Left">
            <img src="/images/main.jpeg" alt="" width={500} />
          </div>
          <div className="Main__Right">
            <h1
              data-aos="fade-up"
              data-aos-anchor-placement="top-center"
              className="Main__Title"
            >
              Luxury Lady
            </h1>
            <div
              className="Main__Text"
              data-aos="fade-left"
              data-aos-anchor="#example-anchor"
              data-aos-offset="500"
              data-aos-duration="500"
            >
              Я рада приветствовать тебя на Luxury Lady - месте, где ты найдешь
              множество полезных советов и инсайтов о том, как притягивать
              мужчин и получать от них подарки. Я знаю, что ты ищешь что-то
              особенное, и именно поэтому я создала этот сайт - чтобы помочь
              тебе стать лучшей версией себя и получать от жизни все, что ты
              заслуживаешь. Давай начнем это увлекательное путешествие вместе!
            </div>
          </div>
        </section>

        <section className="Course" id="course">
          <h2 className="Section__Title">О чем этот курс ?</h2>
          <div className="Course__Text">
            <div className="Course__Text_Item" data-aos="fade-down-right">
              <img src="/images/jewl_icon.svg" alt="" />
              <p>
                Курс от Luxury Lady - это полное руководство, которое поможет
                вам разобраться в тонкостях привлечения и удержания мужчин, а
                также получения от них подарков. Вы узнаете, как улучшить свой
                образ, повысить уверенность в себе и научиться правильно
                общаться с мужчинами.
              </p>
            </div>
            <div className="Course__Text_Item" data-aos="fade-down-left">
              <img src="/images/jewl_icon.svg" alt="" />
              <p>
                Кроме того, вы узнаете множество эффективных советов и приемов,
                которые помогут вам добиться желаемых результатов в отношениях с
                мужчинами и наслаждаться жизнью.
              </p>
            </div>
          </div>
        </section>
        <section className="ForWho">
          <h2 className="Section__Title">Для кого этот курс ?</h2>

          <div className="ForWho__Item">
            <img src="/images/arrow_icon.png" alt="" width={20} />
            <span>
              Для женщин, которые хотят научиться привлекать мужчин и стать
              более уверенными в себе
            </span>
          </div>
          <div className="ForWho__Item">
            <img src="/images/arrow_icon.png" alt="" width={20} />
            <span>
              Для тех, кто ищет новые способы улучшить свою личную жизнь и умеет
              стремиться к лучшему
            </span>
          </div>
          <div className="ForWho__Item">
            <img src="/images/arrow_icon.png" alt="" width={20} />
            <span>
              Для всех, кто хочет научиться получать больше внимания и подарков
              от мужчин
            </span>
          </div>
          <div className="ForWho__Item">
            <img src="/images/arrow_icon.png" alt="" width={20} />
            <span>
              Для тех, кто устал от неудачных попыток завести знакомства и хочет
              научиться привлекать мужчин более эффективно
            </span>
          </div>
          <div className="ForWho__Item">
            <img src="/images/arrow_icon.png" alt="" width={20} />
            <span>
              Для женщин, которые хотят научиться тонкостям флирта и соблазна и
              использовать их в своих отношениях с мужчинами
            </span>
          </div>
        </section>
        <section className="Reviews" id="reviews">
          <h2 className="Section__Title">Отзывы</h2>
          <div className="Reviews__Items">
            <img data-aos="fade-right" src="/images/rev1.jpg" alt="" width={270} />
            <img data-aos="fade-left" src="/images/rev2.jpg" alt="" width={270} />
            <img data-aos="fade-right" src="/images/rev3.jpg" alt="" width={270} />
            <img data-aos="fade-left" src="/images/rev5.jpg" alt="" width={270} />
          </div>
        </section>

        <section className="Price" id="price">
          <h2 className="Section__Title">Стоимость курса</h2>

          <div className="Price__Box" data-aos="flip-down">
            <div className="Price__Box_Item">
              <img src="/images/time.png" alt="" width={60}/>
            <p>
              Обучение длиться от 3 недель до 3 месяцев плюс к концу обучения вы
              приглашаетесь в чат девчонок. Там вы всегда можете
              проконсультироваться с единомышленницами и выйти на стабильный
              уровень подарков и цветов
            </p>
            </div>
            <div className="Price__Box_Item">
            <img src="/images/study1.png" alt="" width={60}/><p>
              К тому же во время обучения, вам скинут скрипты: как экологично
              попросить мужчину о помощи, любую просьбу или так же как правильно
              попросить цветы и подарки
            </p>
            </div>
            <div className="Price__Box_Item">
            <img src="/images/study.png" alt="" width={60}/><p>
              Трёх месячное обучение будет в телеграмме, во время этого периода
              имеется личные консультации, с опытными кураторами
            </p>
            </div>
            
            <div className="Price__Box_Cost">120 $</div>
            <button>Приобрести</button>
          </div>
        </section>
        <section className="Contacts">
          <p>У вас есть вопросы или нужна помощь в выборе курса? 
            Напишите мне в <a href="https://www.instagram.com/luxury_lady____/?igshid=YmMyMTA2M2Y%3D" target="_blank">Instagram</a>  и я с удовольствием вам помогу! Кроме того, на моей странице вы найдете много полезных советов и гайдов по теме притягивания мужчин и получения подарков. Подписывайтесь и не пропустите ничего интересного!</p>
        </section>
      </div>
    </>
  );
}
